# Generated by Django 2.2.9 on 2020-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publish_date', models.DateField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('link', models.TextField(blank=True)),
            ],
        ),
    ]
