# Generated by Django 3.0.4 on 2020-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_coupon_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Latest_Sale',
            new_name='Sale',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='free_game',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
