# Generated by Django 3.0.4 on 2020-07-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200429_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publish_date', models.DateField()),
                ('photo_main', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
        ),
    ]
