# Generated by Django 3.0.4 on 2020-07-06 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_carousel_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
