# Generated by Django 3.0.4 on 2020-03-24 03:31

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publish_date', models.DateField()),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('icon', models.CharField(default='<i class="fab fa-playstation"></i>', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('link', models.TextField(blank=True)),
                ('distribution', models.CharField(choices=[('Dg', 'Digital'), ('Ph', 'Physical')], default='Dg', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.Company')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.Game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.Platform')),
            ],
        ),
    ]
