# Generated by Django 3.0.4 on 2020-03-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='photo_1',
        ),
    ]
