# Generated by Django 2.2.9 on 2020-03-24 10:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200324_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
