# Generated by Django 2.2.9 on 2020-03-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200324_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
