# Generated by Django 3.0.4 on 2020-03-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_link_before_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='found_game',
            field=models.BooleanField(default=True),
        ),
    ]
