# Generated by Django 3.0.4 on 2020-03-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_link_found_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='found_game',
        ),
        migrations.AddField(
            model_name='link',
            name='found_game_price',
            field=models.BooleanField(default=False),
        ),
    ]
