# Generated by Django 3.0.4 on 2020-03-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200325_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='before_discount_price',
            new_name='initial_price',
        ),
    ]
