# Generated by Django 3.0.4 on 2020-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200325_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='company',
            name='photo_url',
            field=models.TextField(default=None, null=True),
        ),
    ]
