# Generated by Django 3.0.4 on 2020-03-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200330_2127'),
    ]

    operations = [
        migrations.RenameModel('Company', 'Store')
    ]
