# Generated by Django 3.0.4 on 2020-03-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20200330_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='company',
            new_name='store',
        ),
    ]
