# Generated by Django 3.0.4 on 2020-03-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20200330_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='found_game_price',
            new_name='is_free',
        ),
    ]
