# Generated by Django 3.0.4 on 2020-03-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20200330_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
