# Generated by Django 3.0.4 on 2020-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_platform_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='price_found',
            field=models.BooleanField(default=False),
        ),
    ]
