# Generated by Django 3.0.4 on 2020-03-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_link_price_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='is_free',
        ),
    ]
