# Generated by Django 3.0.4 on 2020-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_remove_link_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
