# Generated by Django 3.0.4 on 2020-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20200331_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
