# Generated by Django 3.0.4 on 2020-03-31 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_auto_20200331_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
