# Generated by Django 3.0.4 on 2020-03-31 01:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20200331_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 31, 1, 21, 34, 889295, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 31, 1, 21, 34, 889295, tzinfo=utc)),
        ),
    ]
