# Generated by Django 3.0.4 on 2020-03-31 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20200331_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='link',
            name='price_found',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
