# Generated by Django 3.0.4 on 2020-04-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20200331_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='trustpilot_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
