# Generated by Django 3.0.4 on 2020-04-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_store_trustpilot_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='platform',
            name='img_url',
            field=models.CharField(blank=True, default='https://sm.pcmag.com/t/pcmag_au/review/x/xbox-for-p/xbox-for-pc_trav.640.jpg', max_length=200),
        ),
    ]
