# Generated by Django 3.0.4 on 2020-04-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_auto_20200404_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
