# Generated by Django 3.0.4 on 2020-04-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_game_metacritic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='metacritic',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(default=None, to='games.Platform'),
        ),
    ]
