# Generated by Django 3.0.4 on 2020-04-30 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_auto_20200430_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='games.Game'),
        ),
    ]
