# Generated by Django 3.0.4 on 2020-04-30 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_auto_20200430_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheapest_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheapest_links', to='games.Game')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Link')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Platform')),
            ],
        ),
    ]
