# Generated by Django 3.0.4 on 2020-07-10 02:22

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_cheapest_link'),
    ]

    operations = [
        TrigramExtension()
    ]
