# Generated by Django 3.0.4 on 2020-07-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_auto_20200710_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
